<?php
require __DIR__.'/action.class.php';

$action = new Action();

$action->query(
    str_replace('{TABLE_MAIN}', TABLE_MAIN,
        "CREATE TABLE IF NOT EXISTS {TABLE_MAIN} (
            id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name CHARACTER VARYING(80) NOT NULL DEFAULT '',
            contact CHARACTER VARYING(80) NOT NULL DEFAULT '',
            email CHARACTER VARYING(80) NOT NULL DEFAULT '',
            message TEXT NULL DEFAULT NULL,
            time int NOT NULL DEFAULT 0
        );"
    )
);
$action->query(
    str_replace('{TABLE_USERS}', TABLE_USERS,
        "CREATE TABLE IF NOT EXISTS {TABLE_USERS} (
            id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            login CHARACTER VARYING(80) NOT NULL DEFAULT '',
            password CHARACTER VARYING(100) NOT NULL DEFAULT ''
        );"
    )
);
if (!$action->recordExists(['login'=>'admin'],TABLE_USERS)){
    $action->rowInsert(['login'=>'admin', 'password' => 'f766b6dde26c3bdcdbc83029abbd0b6a27e480fe'],TABLE_USERS);
}

echo 'Done!';